import { Button } from '@/components/ui/button'
import { Dumbbell, Users, Brain, TrendingUp } from 'lucide-react'
import Link from 'next/link'

export default function HomePage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-primary-50 to-white">
      {/* Header */}
      <header className="px-6 lg:px-8">
        <div className="mx-auto max-w-7xl">
          <div className="flex h-16 items-center justify-between">
            <div className="flex items-center gap-2">
              <Dumbbell className="h-8 w-8 text-primary-600" />
              <span className="text-2xl font-bold text-gray-900">FitForge</span>
            </div>
            <nav className="hidden md:flex items-center gap-8">
              <Link href="/login" className="text-gray-700 hover:text-primary-600">
                Login
              </Link>
              <Button asChild>
                <Link href="/register">Get Started</Link>
              </Button>
            </nav>
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <main className="px-6 lg:px-8">
        <div className="mx-auto max-w-7xl py-24 sm:py-32">
          <div className="text-center">
            <h1 className="text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl">
              Forge Your Perfect
              <span className="text-primary-600"> Workout</span>
            </h1>
            <p className="mt-6 text-lg leading-8 text-gray-600 max-w-2xl mx-auto">
              Create AI-powered workout plans, track your progress, and connect with a community 
              of fitness enthusiasts. Your personal trainer meets social network.
            </p>
            <div className="mt-10 flex items-center justify-center gap-x-6">
              <Button size="lg" asChild>
                <Link href="/register">Start Your Journey</Link>
              </Button>
              <Button variant="outline" size="lg" asChild>
                <Link href="/login">Sign In</Link>
              </Button>
            </div>
          </div>
        </div>

        {/* Features */}
        <div className="mx-auto max-w-7xl py-24">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-gray-900">Everything You Need to Succeed</h2>
            <p className="mt-4 text-gray-600">Powerful tools to help you reach your fitness goals</p>
          </div>
          
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
            <div className="text-center p-6">
              <Brain className="h-12 w-12 text-primary-600 mx-auto mb-4" />
              <h3 className="text-xl font-semibold text-gray-900 mb-2">AI-Powered Plans</h3>
              <p className="text-gray-600">Get personalized workout plans generated by AI based on your goals and equipment.</p>
            </div>
            
            <div className="text-center p-6">
              <TrendingUp className="h-12 w-12 text-primary-600 mx-auto mb-4" />
              <h3 className="text-xl font-semibold text-gray-900 mb-2">Progress Tracking</h3>
              <p className="text-gray-600">Track your workouts, monitor progress, and get insights to optimize your training.</p>
            </div>
            
            <div className="text-center p-6">
              <Users className="h-12 w-12 text-primary-600 mx-auto mb-4" />
              <h3 className="text-xl font-semibold text-gray-900 mb-2">Social Community</h3>
              <p className="text-gray-600">Follow friends, share workouts, and stay motivated with social accountability.</p>
            </div>
            
            <div className="text-center p-6">
              <Dumbbell className="h-12 w-12 text-primary-600 mx-auto mb-4" />
              <h3 className="text-xl font-semibold text-gray-900 mb-2">Exercise Library</h3>
              <p className="text-gray-600">Access hundreds of exercises with detailed instructions and form tips.</p>
            </div>
          </div>
        </div>

        {/* CTA */}
        <div className="mx-auto max-w-7xl py-24">
          <div className="bg-primary-600 rounded-2xl px-6 py-16 text-center">
            <h2 className="text-3xl font-bold text-white mb-4">Ready to Transform Your Fitness?</h2>
            <p className="text-primary-100 mb-8 max-w-2xl mx-auto">
              Join thousands of users who are already achieving their fitness goals with FitForge.
            </p>
            <Button size="lg" variant="secondary" asChild>
              <Link href="/register">Start Free Trial</Link>
            </Button>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t bg-white">
        <div className="mx-auto max-w-7xl px-6 py-12 lg:px-8">
          <div className="flex items-center justify-center">
            <div className="flex items-center gap-2">
              <Dumbbell className="h-6 w-6 text-primary-600" />
              <span className="text-lg font-semibold text-gray-900">FitForge</span>
            </div>
          </div>
          <p className="mt-4 text-center text-sm text-gray-600">
            © 2024 FitForge. All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  )
}
