import { Button } from '@/components/ui/button'
import { Dumbbell, Users, Zap, TrendingUp } from 'lucide-react'
import Link from 'next/link'

export default function HomePage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100">
      <header className="container mx-auto px-4 py-6">
        <nav className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Dumbbell className="h-8 w-8 text-primary-600" />
            <span className="text-2xl font-bold text-gray-900">FitForge</span>
          </div>
          <div className="flex gap-4">
            <Link href="/login">
              <Button variant="ghost">Sign In</Button>
            </Link>
            <Link href="/register">
              <Button>Get Started</Button>
            </Link>
          </div>
        </nav>
      </header>

      <main className="container mx-auto px-4 py-12">
        <div className="text-center mb-16">
          <h1 className="text-5xl font-bold text-gray-900 mb-6">
            AI-Powered Fitness
            <span className="text-primary-600"> Made Social</span>
          </h1>
          <p className="text-xl text-gray-600 mb-8 max-w-2xl mx-auto">
            Create personalized workout plans, track your progress, and get AI coaching 
            while staying motivated with a community of fitness enthusiasts.
          </p>
          <Link href="/register">
            <Button size="lg" className="text-lg px-8 py-3">
              Start Your Journey
            </Button>
          </Link>
        </div>

        <div className="grid md:grid-cols-3 gap-8 mb-16">
          <div className="text-center p-6">
            <Zap className="h-12 w-12 text-primary-600 mx-auto mb-4" />
            <h3 className="text-xl font-semibold mb-2">AI Workout Plans</h3>
            <p className="text-gray-600">
              Get personalized workouts generated by AI based on your goals, 
              experience, and available equipment.
            </p>
          </div>
          
          <div className="text-center p-6">
            <TrendingUp className="h-12 w-12 text-primary-600 mx-auto mb-4" />
            <h3 className="text-xl font-semibold mb-2">Track Progress</h3>
            <p className="text-gray-600">
              Monitor your strength gains, analyze trends, and get AI insights 
              to optimize your training.
            </p>
          </div>
          
          <div className="text-center p-6">
            <Users className="h-12 w-12 text-primary-600 mx-auto mb-4" />
            <h3 className="text-xl font-semibold mb-2">Social Motivation</h3>
            <p className="text-gray-600">
              Follow other users, share workouts, and stay accountable with 
              likes and comments.
            </p>
          </div>
        </div>

        <div className="bg-white rounded-lg shadow-lg p-8 text-center">
          <h2 className="text-3xl font-bold mb-4">Ready to Transform?</h2>
          <p className="text-gray-600 mb-6">
            Join thousands of users who are already crushing their fitness goals with FitForge.
          </p>
          <Link href="/register">
            <Button size="lg">
              Create Free Account
            </Button>
          </Link>
        </div>
      </main>

      <footer className="container mx-auto px-4 py-8 mt-16 border-t">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Dumbbell className="h-6 w-6 text-primary-600" />
            <span className="font-semibold">FitForge</span>
          </div>
          <p className="text-sm text-gray-600">
            © 2024 FitForge. All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  )
}
